In [13]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [14]:
env = gym.make("Taxi-v3")

In [15]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [16]:
num_episodes = 10000
max_num_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [17]:
rewards_all_episodes = []

# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_num_steps_per_episode):
        
        #exploration -- exploitation tradeoff
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate and ~np.all(q_table[state,:]==0):
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        #update q_table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
                learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
            
    #exploration decay rate
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  -250.17699999999962
2000 :  -38.45099999999998
3000 :  1.8689999999999953
4000 :  5.608999999999976
5000 :  6.990999999999959
6000 :  7.20699999999997
7000 :  7.461999999999969
8000 :  7.430999999999963
9000 :  7.4919999999999645
10000 :  7.487999999999963


In [18]:
print(q_table)

[[  0.           0.           0.           0.           0.
    0.        ]
 [  0.91320681   0.3503855   -0.86333913  -1.88901085   9.6220697
   -5.86538482]
 [  4.86532002   6.46881769   0.2337967    6.04855131  14.11880599
   -4.74135387]
 ...
 [ -1.54506415  -1.45434352  -1.51590651   4.36973271  -7.20853707
   -8.02574321]
 [ -2.86243587  -2.86528426  -2.87935691   4.56232428 -10.82319849
  -10.70596788]
 [  0.12746223   2.08724996  -0.29872     17.69034815  -2.2614243
   -5.00855734]]


In [29]:
for episode in range(1000):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_num_steps_per_episode):        
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 20:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****goal missed!****")
                time.sleep(3)
                clear_output(wait=True)
            break            

        # Set new state
        state = new_state
        
env.close()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



KeyboardInterrupt: 

In [28]:
#for a particular episode
episode=90
state = env.reset()
done = False
#print("*****EPISODE ", episode+1, "*****\n\n\n\n")
time.sleep(1)

for step in range(max_num_steps_per_episode):        
    clear_output(wait=True)
    env.render()
    time.sleep(0.3)
        
    action = np.argmax(q_table[state,:])        
    new_state, reward, done, info = env.step(action)
        
    if done:
        clear_output(wait=True)
        env.render()
        if reward == 20:
            print("****You reached the goal!****")
            time.sleep(3)
        else:
            print("****goal missed!****")
            time.sleep(3)
            clear_output(wait=True)
        break            

    # Set new state
    state = new_state
        
env.close()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
****You reached the goal!****
